apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-reverseproxy
  labels:
    app: udagram-api-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-api-reverseproxy
    spec:
      containers:
        - name: api-reverseproxy
          image: anileloye/reverseproxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              # memory: "64Mi"
              cpu: "500m"
            limits:
              # memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 80
      restartPolicy: Always
