version: "3"
services:
  api-user:
    restart: on-failure
    build: ./udagram-api-user
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    image: api-user:latest
  api-feed:
    restart: on-failure
    build: ./udagram-api-feed
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    image: api-feed:latest
  frontend:
    restart: on-failure
    build: ./udagram-frontend
    ports:
      - "80:80"
    image: frontend:latest
  reverseproxy:
    build: ./udagram-reverseproxy
    ports:
      - "8080:8080"
    depends_on:
      - api-user
      - api-feed
    image: reverseproxy:latest
