version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: |
          docker-compose -f docker-compose.yaml build --parallel
          docker tag udagram-api-user ${DOCKERHUB_USERNAME}/latest
          docker tag udagram-api-feed ${DOCKERHUB_USERNAME}/latest
          docker tag udagram-frontend ${DOCKERHUB_USERNAME}/latest
          docker tag udagram-reverseproxy ${DOCKERHUB_USERNAME}/latest
          echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” --password-stdin
          docker push ${DOCKERHUB_USERNAME}/latest
          docker push ${DOCKERHUB_USERNAME}/latest
          docker push ${DOCKERHUB_USERNAME}/latest
          docker push ${DOCKERHUB_USERNAME}/latest
