version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: |
          docker-compose -f docker-compose.yaml build --parallel
          docker tag api-user api-user/latest
          docker tag api-feed api-feed/latest
          docker tag frontend frontend/latest
          docker tag reverseproxy reverseproxy/latest
          echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” --password-stdin
          docker push api-user/latest
          docker push api-feed/latest
          docker push frontend/latest
          docker push reverseproxy/latest
