version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: |
          docker-compose -f docker-compose.yaml build --parallel
          echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” --password-stdin
          docker image tag api-user:latest api-user/$DOCKER_USERNAME/api-user:latest
          docker image push api-user/$DOCKER_USERNAME/api-user:latest
          docker image tag api-feed:latest api-feed/$DOCKER_USERNAME/api-feed:latest
          docker image push api-feed/$DOCKER_USERNAME/api-feed:latest
          docker image tag frontend:latest frontend/$DOCKER_USERNAME/frontend:latest
          docker image push frontend/$DOCKER_USERNAME/frontend:latest
          docker image tag reverseproxy:latest reverseproxy/$DOCKER_USERNAME/reverseproxy:latest
          docker image push reverseproxy/$DOCKER_USERNAME/reverseproxy:latest
