version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: |
          docker-compose -f docker-compose.yaml build --parallel
          echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” --password-stdin
          docker tag api-user anileloye/api-user:latest
          docker tag api-feed anileloye/api-feed:latest
          docker tag frontend anileloye/frontend:latest
          docker tag reverseproxy anileloye/reverseproxy:latest
          docker push anileloye/frontend
          docker push anileloye/frontend
          docker push anileloye/frontend
          docker push anileloye/frontend
