apiVersion: v1
kind: Service
metadata:
  name: udagram-api-users-svc
  labels:
    app: udagram-api-users
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
  selector:
    app: udagram-api-users
